import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {renderCollections} from '../src/components/collections.mjs';
test('notice fashion is page-scoped, readable, responsive and preserves native disclosure',async()=>{
 const css=await readFile(new URL('../public/assets/css/notice-fashion.css',import.meta.url),'utf8');
 assert.ok(css.includes('body:has(.notice-section)'));
 assert.ok(!css.includes('url('));
 assert.ok(css.includes('summary:focus-visible'));
 assert.ok(css.includes('grid-column:1/span 2'));
 assert.ok(css.includes('filter:none;opacity:1'));
 assert.ok(!css.includes('object-fit:cover'));
 const page=JSON.parse(await readFile(new URL('../src/pages/notice.json',import.meta.url),'utf8'));
 const notices=JSON.parse(await readFile(new URL('../src/data/notices.json',import.meta.url),'utf8'));
 assert.equal(notices.length,34);
 const html=renderCollections(page.contentHtml,{notices});
 assert.ok(html.includes('전체 공지 34건'));
 assert.equal((html.match(/class="notice-item reveal"/g)||[]).length,34);
 assert.equal((html.match(/class="notice-year-group"/g)||[]).length,5);
 const renderedIds=[...html.matchAll(/<details\b[^>]*\bid="([^"]+)"/g)].map(match=>match[1]);
 assert.deepEqual(renderedIds,notices.toSorted((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id)).map(notice=>notice.id));
 assert.ok(html.indexOf('notice-year-2030')<html.indexOf('notice-year-2029'));
 assert.ok(html.indexOf('return-2030-release')<html.indexOf('night-in-the-house-2030'));
 assert.equal(notices.find(({id})=>id==='return-2030-release')?.href,'return-2030.html');
 assert.equal(notices.find(({id})=>id==='night-in-the-house-2030')?.href,'night-in-the-house-2030.html');
 assert.equal(notices.filter(({id})=>id==='sometime-release').length,1);
 const luna7=notices.find(({id})=>id==='luna7-membership');
 assert.ok(luna7);
 assert.equal(luna7.attributesHtml.includes('data-notice-category="fanclub"'),true);
 assert.ok(luna7.bodyTemplateHtml.includes('<time>2029.11.20</time>'));
 assert.ok(luna7.bodyTemplateHtml.includes('href="luna7.html"'));
 for(const notice of notices)assert.ok(notice.bodyTemplateHtml.includes('<summary>'));
});
