import {useEffect} from 'react';

function EditorialFeature(){return <section className="section home-editorial"><div className="container home-editorial-inner"><div><span className="section-kicker">NIGHT EDITORIAL</span><h2>FIVE VOICES</h2></div><div><p>다섯 멤버가 말하는 지금의 NIGHT. 무대 위의 모습과 무대 밖의 시간을 인터뷰에서 만나보세요.</p><a className="btn" href="five-voices.html">READ THE INTERVIEW →</a></div></div></section>;}

function Hero() { return (<section className={"hero"}>{"\n"}<img alt={"NIGHT 단체 이미지"} className={"hero-image"} src={"assets/images/home-hero-night.webp"} width={"1672"} height={"941"} fetchPriority={"high"} decoding={"async"} />{"\n"}<div className={"hero-content"}>{"\n"}<p className={"eyebrow"}>{"Castle Entertainment · 5 Member Group"}</p>{"\n"}<h1 className={"hero-title"}>{"NIGHT"}</h1>{"\n"}<p className={"hero-debut"}>{"DEBUT · 2022.11.15"}</p>{"\n"}<p className={"hero-copy"}>{"강렬한 퍼포먼스와 도시적인 비주얼로 데뷔해, 앨범마다 새로운 음악과 무대를 선보여온 5인조 아이돌 그룹."}</p>{"\n"}<p className={"hero-slogan"}>{"WHEN THE NIGHT FALLS, WE SHINE."}</p>{"\n"}<div className={"cta-row"}>{"\n"}<a className={"btn"} href={"#members"}>{"MEET THE MEMBERS"}</a>{"\n"}<a className={"btn secondary"} href={"fanclub.html"}>{"OFFICIAL FANCLUB"}</a>{"\n"}</div>{"\n"}</div>{"\n"}</section>); }

function About() { return (<section className={"section"}>{"\n"}<div className={"container about-grid reveal"}>{"\n"}<div className={"about-visual"}><img alt={"NIGHT 멤버 프로필 이미지"} src={"assets/images/home-about-night.webp"} width={"512"} height={"341"} loading={"lazy"} decoding={"async"} /></div>{"\n"}<div className={"about-copy"}>{"\n"}<span className={"section-kicker"}>{"About NIGHT"}</span>{"\n"}<h2 className={"section-title"}>{"The irreplaceable idols."}</h2>{"\n"}<p>{"NIGHT는 CASTLE Entertainment 소속의 5인조 아이돌 그룹이다."}</p>{"\n"}<p>{"데뷔 초반 섹시 콘셉트와 강렬한 무대 장악력을 앞세워, 데뷔 약 10일 만에 Billboard Global Excl. U.S.에 처음 진입하며 빠르게 주목받았다."}</p>{"\n"}<p>{"이후 다양한 음악과 콘셉트를 선보이며 NIGHT만의 스타일을 만들어왔다."}</p>{"\n"}<p>{"NIGHT의 중심에는 언제나 다섯 멤버가 있다."}</p>{"\n"}<p>{"서로 다른 다섯 멤버의 개성과 표현 방식은 한 무대에서 NIGHT만의 색으로 이어진다."}</p>{"\n"}<p>{"다섯 사람이 함께할 때 가장 선명해지는 팀."}</p>{"\n"}<p>{"그것이 NIGHT다."}</p>{"\n"}<div style={{margin:"24px 0 30px"}}><a className={"btn secondary"} href={"about-night.html"}>{"ABOUT NIGHT →"}</a></div>{"\n"}<div className={"stats"}><div className={"stat"}><strong>{"5"}</strong><span>{"CURRENT MEMBERS"}</span></div><div className={"stat"}><strong>{"10D"}</strong><span>{"TO BILLBOARD ENTRY"}</span></div><div className={"stat"}><strong>{"2022—"}</strong><span>{"SINCE DEBUT"}</span></div></div>{"\n"}</div></div></section>); }

function Members() { return (<section className={"section"} id={"members"}><div className={"container"}><div className={"section-head reveal"}><div><span className={"section-kicker"}>{"Current Line-up"}</span><h2 className={"section-title"}>{"Members"}</h2></div><p className={"section-desc"}>{"서로 다른 매력으로 NIGHT를 완성하는 다섯 멤버를 만나보세요."}</p></div><div className={"member-grid"}><a className={"member-card reveal"} href={"member-doha.html"}><img alt={"윤도하"} src={"assets/images/home-profile-doha.webp"} width={"1122"} height={"1402"} loading={"lazy"} decoding={"async"} /><div className={"member-info"}><div className={"member-role"}>{"Leader · Sub Rapper"}</div><h3 className={"member-name"}>{"윤도하"}</h3><div className={"member-eng"}>{"YOON DOHA"}</div></div></a><a className={"member-card reveal"} href={"member-woohyun.html"}><img alt={"성우현"} src={"assets/images/home-profile-woohyun.webp"} width={"1122"} height={"1402"} loading={"lazy"} decoding={"async"} /><div className={"member-info"}><div className={"member-role"}>{"Main Dancer"}</div><h3 className={"member-name"}>{"성우현"}</h3><div className={"member-eng"}>{"SUNG WOOHYUN"}</div></div></a><a className={"member-card reveal"} href={"member-jiwoo.html"}><img alt={"천지우"} src={"assets/images/home-profile-jiwoo.webp"} width={"1122"} height={"1402"} loading={"lazy"} decoding={"async"} /><div className={"member-info"}><div className={"member-role"}>{"Center · Main Rapper"}</div><h3 className={"member-name"}>{"천지우"}</h3><div className={"member-eng"}>{"CHEON JIWOO"}</div></div></a><a className={"member-card reveal"} href={"member-ihwan.html"}><img alt={"박이환"} src={"assets/images/home-profile-ihwan.webp"} width={"1122"} height={"1402"} loading={"lazy"} decoding={"async"} /><div className={"member-info"}><div className={"member-role"}>{"Main Vocal"}</div><h3 className={"member-name"}>{"박이환"}</h3><div className={"member-eng"}>{"PARK IHWAN"}</div></div></a><a className={"member-card reveal"} href={"member-taehoon.html"}><img alt={"유태훈"} src={"assets/images/home-profile-taehoon.webp"} width={"1122"} height={"1402"} loading={"lazy"} decoding={"async"} /><div className={"member-info"}><div className={"member-role"}>{"Lead Vocal · Maknae"}</div><h3 className={"member-name"}>{"유태훈"}</h3><div className={"member-eng"}>{"YOO TAEHOON"}</div></div></a></div></div></section>); }

function LatestMusic() { return (<section className={"section phantom-comeback-home"}><div className={"container phantom-comeback-grid reveal"}><div className={"phantom-comeback-copy"}><span className={"section-kicker"}>{"Latest Release · Digital Single"}</span><h2 className={"section-title"}>{"REST"}</h2><p className={"phantom-home-tagline"}>{"NEXT TIME · 2029.11.02"}</p><p className={"phantom-home-desc"}>{"잠시 멈춰 쉬어가도 괜찮다는 마음을 담은 NIGHT의 디지털 싱글. 잔잔하게 이어지는 "}<strong>{"NEXT TIME"}</strong>{"을 지금 들어보세요."}</p><div className={"phantom-release-meta"}><span>{"DIGITAL SINGLE"}</span><span>{"LATEST · 2029.11.02"}</span></div><div className={"phantom-release-actions"}><a className={"btn"} href={"listen.html#next-time"}>{"LISTEN TO NEXT TIME"}</a><a className={"btn secondary"} href={"discography.html#rest"}>{"VIEW DISCOGRAPHY"}</a></div></div><a className={"phantom-scheduler-card"} href={"discography.html#rest"} aria-label={"REST 디지털 싱글 정보 보기"}><img src={"assets/images/2029/rest/next-time.webp"} alt={"REST · NEXT TIME"} loading={"lazy"} decoding={"async"} /></a></div></section>); }

function ArchiveLinks() { return (<section className={"section home-archive"}><div className={"container"}><div className={"section-head reveal"}><div><span className={"section-kicker"}>{"Explore NIGHT"}</span><h2 className={"section-title"}>{"Explore the Night."}</h2></div><p className={"section-desc"}>{"앨범과 공연, 공식 콘텐츠와 최신 소식까지 NIGHT의 활동을 한곳에서 만나보세요."}</p></div><div className={"home-archive-grid"}><a className={"home-archive-card reveal"} href={"discography.html"}><span className={"archive-no"}>{"01"}</span><small>{"MUSIC"}</small><h3>{"Discography"}</h3><p>{"발매일, 타이틀곡과 트랙리스트를 포함한 NIGHT의 앨범을 만나보세요."}</p><strong>{"VIEW DISCOGRAPHY →"}</strong></a><a className={"home-archive-card reveal"} href={"history.html"}><span className={"archive-no"}>{"02"}</span><small>{"TIMELINE"}</small><h3>{"History"}</h3><p>{"데뷔부터 앨범, 공연, 팬클럽 활동까지 NIGHT의 주요 순간을 시간순으로 확인하세요."}</p><strong>{"VIEW HISTORY →"}</strong></a><a className={"home-archive-card reveal"} href={"listen.html"}><span className={"archive-no"}>{"03"}</span><small>{"TITLE TRACKS"}</small><h3>{"Listen"}</h3><p>{"발매 순서대로 NIGHT의 타이틀곡을 듣고 각 음원의 정보를 확인하세요."}</p><strong>{"LISTEN NOW →"}</strong></a><a className={"home-archive-card reveal"} href={"gallery.html"}><span className={"archive-no"}>{"04"}</span><small>{"OFFICIAL PHOTOS"}</small><h3>{"Gallery"}</h3><p>{"콘셉트 포토와 활동 사진, 다양한 공식 비주얼을 모아보세요."}</p><strong>{"VIEW GALLERY →"}</strong></a><a className={"home-archive-card home-contents-card reveal"} href={"contents.html"}><span className={"archive-no"}>{"05"}</span><small>{"ORIGINALS · VLOG · TRAVEL · BEHIND"}</small><h3>{"Contents"}</h3><p>{"자체 콘텐츠와 브이로그, 여행, 비하인드, 팬미팅까지 무대 밖 NIGHT의 이야기를 만나보세요."}</p><strong>{"EXPLORE CONTENTS →"}</strong></a><a className={"home-archive-card reveal"} href={"notice.html"}><span className={"archive-no"}>{"06"}</span><small>{"OFFICIAL UPDATES"}</small><h3>{"Notice"}</h3><p>{"앨범, 공연, 팬클럽과 사이트 업데이트 등 NIGHT의 공식 소식을 확인하세요."}</p><strong>{"VIEW NOTICE →"}</strong></a></div><div className={"home-search-entry"}><a className={"btn"} href={"archive.html"}>{"SEARCH NIGHT →"}</a></div><div className={"home-archive-shortcuts"}><a className={"home-era-shortcut reveal"} href={"era-archive.html"}><span><small>{"NIGHT TIMELINE"}</small><strong>{"Every era. One continuous night."}</strong></span><b>{"EXPLORE THE TIMELINE →"}</b></a><a className={"home-era-shortcut home-awards-shortcut reveal"} href={"awards.html"}><span><small>{"CAREER · 2022—2029"}</small><strong>{"Awards & Achievements"}</strong></span><b>{"VIEW ACHIEVEMENTS →"}</b></a></div></div></section>); }

function Fanclub() { return (<section className={"section-tight"}><div className={"container fanclub-banner reveal"}><img alt={"NIGHT 공식 응원봉 MOONLIGHT"} src={"assets/images/night-luna.webp"} width={"900"} height={"900"} loading={"lazy"} decoding={"async"} /><div className={"fanclub-copy"}><span className={"section-kicker"}>{"Official Fanclub"}</span><h3>{"Under the same night."}</h3><p>{"NIGHT와 LUNA가 같은 밤을 공유하는 공간. 공식 팬클럽과 응원봉 MOONLIGHT의 이야기와 디테일을 만나보세요."}</p><a className={"btn"} href={"fanclub.html"}>{"ENTER FANCLUB"}</a></div></div></section>); }

function HomeGuide({updates}){return <section className="section-tight home-guide"><div className="container"><div className="home-guide-intro"><span className="section-kicker">START HERE</span><h2>어떤 NIGHT를 찾고 있나요?</h2><p>앨범 정보는 디스코그래피, 사진은 갤러리, 인터뷰와 일상 이야기는 콘텐츠에서 확인하세요.</p><form action="archive.html" role="search"><label htmlFor="home-query">사이트 검색</label><div><input id="home-query" type="search" name="q" placeholder="앨범·멤버·콘텐츠 이름"/><button type="submit">검색 →</button></div></form></div><div className="home-updates"><div className="section-head"><h2>최근 공식 공지</h2><a href="notice.html">전체 공지 →</a></div><p>팬클럽, 행사와 콘텐츠의 최근 소식을 확인하세요. 앨범 발매 정보는 디스코그래피에서 볼 수 있습니다.</p><ul>{updates.map(item=><li key={item.id}><a href={item.href}><span>{item.date}</span><strong>{item.title}</strong><span aria-hidden="true">↗</span></a></li>)}</ul></div></div></section>;}
export function HomePage({updates=[]}) {
  useEffect(() => {
    const elements = document.querySelectorAll("#night-react-root .reveal");
    if (!("IntersectionObserver" in window)) { elements.forEach(el => el.classList.add("is-visible")); return; }
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), {threshold:0.12});
    elements.forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, []);
  return <><Hero/><LatestMusic/><About/><Members/><EditorialFeature/><ArchiveLinks/><HomeGuide updates={updates}/><Fanclub/></>;
}
