import {useEffect} from 'react';

function EditorialFeature(){return <section className="section home-editorial"><div className="container home-editorial-inner"><div><span className="section-kicker">NIGHT EDITORIAL</span><h2>FIVE VOICES</h2></div><div><p>다섯 멤버가 말하는 지금의 NIGHT. 무대 위의 정체성과 무대 밖의 시간을 인터뷰에서 만나보세요.</p><a className="btn" href="five-voices.html">READ THE INTERVIEW →</a></div></div></section>;}

function Hero() { return (<section className={"hero"}>{"\n"}<img alt={"NIGHT 단체 이미지"} className={"hero-image"} src={"assets/images/night-group-main.png"} />{"\n"}<div className={"hero-content"}>{"\n"}<p className={"eyebrow"}>{"Castle Entertainment · 5 Member Group"}</p>{"\n"}<h1 className={"hero-title"}>{"NIGHT"}</h1>{"\n"}<p className={"hero-debut"}>{"DEBUT · 2022.11.15"}</p>{"\n"}<p className={"hero-copy"}>{"무대 위의 밤을 지배하는 대체불가 5인조 아이돌 그룹. 강렬한 퍼포먼스와 독보적인 존재감으로 데뷔 이후 정상의 자리를 이어가고 있다."}</p>{"\n"}<p className={"hero-slogan"}>{"WHEN THE NIGHT FALLS, WE SHINE."}</p>{"\n"}<div className={"cta-row"}>{"\n"}<a className={"btn"} href={"#members"}>{"MEET THE MEMBERS"}</a>{"\n"}<a className={"btn secondary"} href={"fanclub.html"}>{"OFFICIAL FANCLUB"}</a>{"\n"}</div>{"\n"}</div>{"\n"}</section>); }

function About() { return (<section className={"section"}>{"\n"}<div className={"container about-grid reveal"}>{"\n"}<div className={"about-visual"}><img alt={"NIGHT 멤버 프로필 이미지"} src={"assets/images/night-group-profile.png"} /></div>{"\n"}<div className={"about-copy"}>{"\n"}<span className={"section-kicker"}>{"About NIGHT"}</span>{"\n"}<h2 className={"section-title"}>{"The irreplaceable idols."}</h2>{"\n"}<p>{"NIGHT는 CASTLE Entertainment 소속의 5인조 아이돌 그룹이다. 섹시 콘셉트와 강렬한 무대 장악력으로 데뷔 약 10일 만에 Billboard Global Excl. U.S.에 처음 진입하며 빠르게 주목받았다."}</p>{"\n"}<p>{"앨범과 공연, 다양한 공식 콘텐츠를 통해 활동 영역을 넓혀 왔다. 멤버 각자의 뚜렷한 개성과 무대 위 시너지가 NIGHT만의 색을 만든다."}</p>{"\n"}<div className={"stats"}><div className={"stat"}><strong>{"5"}</strong><span>{"CURRENT MEMBERS"}</span></div><div className={"stat"}><strong>{"10D"}</strong><span>{"TO BILLBOARD ENTRY"}</span></div><div className={"stat"}><strong>{"6Y"}</strong><span>{"CAREER"}</span></div></div>{"\n"}</div></div></section>); }

function Members() { return (<section className={"section"} id={"members"}><div className={"container"}><div className={"section-head reveal"}><div><span className={"section-kicker"}>{"Current Line-up"}</span><h2 className={"section-title"}>{"Members"}</h2></div><p className={"section-desc"}>{"현재 NIGHT를 구성하는 다섯 멤버. 카드를 선택하면 각 멤버의 소개 페이지로 이동한다."}</p></div><div className={"member-grid"}><a className={"member-card reveal"} href={"member-doha.html"}><img alt={"윤도하"} src={"assets/images/doha.png"} /><div className={"member-info"}><div className={"member-role"}>{"Leader · Sub Rapper"}</div><h3 className={"member-name"}>{"윤도하"}</h3><div className={"member-eng"}>{"YOON DOHA"}</div></div></a><a className={"member-card reveal"} href={"member-ihwan.html"}><img alt={"박이환"} src={"assets/images/ihwan.png"} /><div className={"member-info"}><div className={"member-role"}>{"Main Vocal"}</div><h3 className={"member-name"}>{"박이환"}</h3><div className={"member-eng"}>{"PARK IHWAN"}</div></div></a><a className={"member-card reveal"} href={"member-jiwoo.html"}><img alt={"천지우"} src={"assets/images/jiwoo.png"} /><div className={"member-info"}><div className={"member-role"}>{"Center · Main Rapper"}</div><h3 className={"member-name"}>{"천지우"}</h3><div className={"member-eng"}>{"CHEON JIWOO"}</div></div></a><a className={"member-card reveal"} href={"member-taehun.html"}><img alt={"유태훈"} src={"assets/images/taehun.png"} /><div className={"member-info"}><div className={"member-role"}>{"Lead Vocal · Maknae"}</div><h3 className={"member-name"}>{"유태훈"}</h3><div className={"member-eng"}>{"YOO TAEHOON"}</div></div></a><a className={"member-card reveal"} href={"member-woohyun.html"}><img alt={"성우현"} src={"assets/images/woohyun.png"} /><div className={"member-info"}><div className={"member-role"}>{"Main Dancer"}</div><h3 className={"member-name"}>{"성우현"}</h3><div className={"member-eng"}>{"SUNG WOOHYUN"}</div></div></a></div></div></section>); }

function Anniversary() { return (<section className={"section phantom-comeback-home"}><div className={"container phantom-comeback-grid reveal"}><div className={"phantom-comeback-copy"}><span className={"section-kicker"}>{"Archive Feature · 5th Anniversary"}</span><h2 className={"section-title"}>{"FIVE YEARS. ONE NIGHT."}</h2><p className={"phantom-home-tagline"}>{"2022.11.15 — 2027.11.15"}</p><p className={"phantom-home-desc"}>{"NIGHT의 다섯 해를 하나의 밤으로 연결한 "}<strong>{"5TH ANNIVERSARY POP-UP"}</strong>{". 여덟 개의 공간과 공식 단체 비주얼을 아카이브에서 만나보세요."}</p><div className={"phantom-release-meta"}><span>{"OPENED 2027.11.15"}</span><span>{"8 ZONES · 9 IMAGES"}</span></div><div className={"phantom-release-actions"}><a className={"btn"} href={"fifth-anniversary-2027.html"}>{"ENTER THE POP-UP"}</a><a className={"btn secondary"} href={"contents.html"}>{"VIEW 2027 ARCHIVES"}</a></div></div><a className={"phantom-scheduler-card"} href={"fifth-anniversary-2027.html"} aria-label={"NIGHT 5주년 팝업스토어 아카이브 열기"}><img src={"assets/images/2027/fifth-anniversary/fifthann-001.webp"} alt={"NIGHT 5주년 팝업스토어 입구"} loading={"lazy"} /></a></div></section>); }

function ArchiveLinks() { return (<section className={"section home-archive"}><div className={"container"}><div className={"section-head reveal"}><div><span className={"section-kicker"}>{"NIGHT Archive"}</span><h2 className={"section-title"}>{"Explore the Night."}</h2></div><p className={"section-desc"}>{"음악과 활동 기록, 공식 콘텐츠와 최신 소식까지 NIGHT의 모든 아카이브를 한곳에서 확인할 수 있다."}</p></div><div className={"home-archive-grid"}><a className={"home-archive-card reveal"} href={"discography.html"}><span className={"archive-no"}>{"01"}</span><small>{"MUSIC ARCHIVE"}</small><h3>{"Discography"}</h3><p>{"앨범 소개, 발매일과 타이틀곡, 트랙리스트는 DISCOGRAPHY에서 확인하세요."}</p><strong>{"VIEW DISCOGRAPHY →"}</strong></a><a className={"home-archive-card reveal"} href={"history.html"}><span className={"archive-no"}>{"02"}</span><small>{"TIMELINE"}</small><h3>{"History"}</h3><p>{"데뷔와 멤버 변화, 공연과 팬클럽까지 이어지는 NIGHT의 공식 활동 연혁."}</p><strong>{"VIEW HISTORY →"}</strong></a><a className={"home-archive-card reveal"} href={"listen.html"}><span className={"archive-no"}>{"03"}</span><small>{"TITLE TRACKS"}</small><h3>{"Listen"}</h3><p>{"각 시대의 타이틀곡과 음원 제공 안내를 확인하는 NIGHT의 음악 아카이브."}</p><strong>{"LISTEN NOW →"}</strong></a><a className={"home-archive-card reveal"} href={"gallery.html"}><span className={"archive-no"}>{"04"}</span><small>{"OFFICIAL VISUAL ARCHIVE"}</small><h3>{"Gallery"}</h3><p>{"콘셉트 포토와 공식 활동, 캠페인으로 이어지는 NIGHT의 비주얼 기록."}</p><strong>{"VIEW GALLERY →"}</strong></a><a className={"home-archive-card home-contents-card reveal"} href={"contents.html"}><span className={"archive-no"}>{"05"}</span><small>{"ORIGINALS · VLOG · TRAVEL · BEHIND"}</small><h3>{"Contents"}</h3><p>{"자체 콘텐츠와 브이로그, 여행, 비하인드, 팬미팅까지 무대 밖 NIGHT의 모든 이야기."}</p><strong>{"EXPLORE CONTENTS →"}</strong></a><a className={"home-archive-card reveal"} href={"notice.html"}><span className={"archive-no"}>{"06"}</span><small>{"OFFICIAL UPDATES"}</small><h3>{"Notice"}</h3><p>{"공식 발간물, 팬클럽과 사이트 업데이트 등 NIGHT의 최신 공지."}</p><strong>{"VIEW NOTICE →"}</strong></a></div><div className={"home-search-entry"}><a className={"btn"} href={"archive.html"}>{"SEARCH ALL ARCHIVES →"}</a></div><div className={"home-archive-shortcuts"}><a className={"home-era-shortcut reveal"} href={"era-archive.html"}><span><small>{"NIGHT ERA ARCHIVE"}</small><strong>{"Every era. One continuous night."}</strong></span><b>{"EXPLORE THE TIMELINE →"}</b></a><a className={"home-era-shortcut home-awards-shortcut reveal"} href={"awards.html"}><span><small>{"CAREER RECORD · 2022—2029"}</small><strong>{"Awards & Achievements"}</strong></span><b>{"OPEN THE RECORD →"}</b></a></div></div></section>); }

function Fanclub() { return (<section className={"section-tight"}><div className={"container fanclub-banner reveal"}><img alt={"NIGHT 공식 응원봉 MOONLIGHT"} src={"assets/images/night-luna.png"} /><div className={"fanclub-copy"}><span className={"section-kicker"}>{"Official Fanclub"}</span><h3>{"Under the same night."}</h3><p>{"NIGHT와 팬이 같은 밤을 공유하는 공간. 공식 팬클럽 LUNA와 응원봉 MOONLIGHT의 콘셉트 및 디테일을 확인할 수 있다."}</p><a className={"btn"} href={"fanclub.html"}>{"ENTER FANCLUB"}</a></div></div></section>); }

function HomeGuide({updates}){return <section className="section-tight home-guide"><div className="container"><div className="home-guide-intro"><span className="section-kicker">START HERE</span><h2>어떤 NIGHT를 찾고 있나요?</h2><p>앨범 정보는 디스코그래피, 사진은 갤러리, 인터뷰와 일상 이야기는 콘텐츠에서 확인하세요.</p><form action="archive.html" role="search"><label htmlFor="home-query">전체 아카이브 검색</label><div><input id="home-query" type="search" name="q" placeholder="앨범·멤버·콘텐츠 이름"/><button type="submit">검색 →</button></div></form></div><div className="home-updates"><div className="section-head"><h2>최근 공식 공지</h2><a href="notice.html">전체 공지 →</a></div><p>기존 공지 중 팬클럽·행사·콘텐츠 소식을 날짜순으로 보여드립니다. 앨범 소식은 디스코그래피에서 확인하세요.</p><ul>{updates.map(item=><li key={item.id}><a href={item.href}><span>{item.date}</span><strong>{item.title}</strong><span aria-hidden="true">↗</span></a></li>)}</ul></div></div></section>;}
export function HomePage({updates=[]}) {
  useEffect(() => {
    const elements = document.querySelectorAll("#night-react-root .reveal");
    if (!("IntersectionObserver" in window)) { elements.forEach(el => el.classList.add("is-visible")); return; }
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), {threshold:0.12});
    elements.forEach(el => observer.observe(el));
    const anchor = window.location.hash.slice(1);
    if (anchor) document.getElementById(anchor)?.scrollIntoView();
    return () => observer.disconnect();
  }, []);
  return <main><Hero /><About /><Members /><EditorialFeature /><Anniversary /><ArchiveLinks /><HomeGuide updates={updates}/><Fanclub /></main>;
}
