import {useEffect,useRef,useState} from 'react';
import {clock,secondsPerScene,vlogReaction} from './photo-data.mjs';
import {usePhotoPlayer} from './usePhotoPlayer.jsx';
import {CollectionPhotoDialog} from './CollectionPhotoDialog.jsx';
import {CollectionPhotoCard as PhotoCard} from './CollectionPhotoCard.jsx';
import {imageProps} from './image-props.mjs';
export function PhotoEpisodePage({route,originalData,dimensions={}}){
  const episodes=route==='vlog.html'?originalData.vlogs:originalData.originals;
  const [selected,setSelected]=useState(episodes[0].id);
  const restoreFocus=useRef(false);
  useEffect(()=>{
    if(route!=='night-originals.html')return;
    let raf;
    const scroll=()=>{if(location.hash==='#for-luna')raf=requestAnimationFrame(()=>document.getElementById('for-luna')?.scrollIntoView());};
    scroll();window.addEventListener('hashchange',scroll);
    return ()=>{cancelAnimationFrame(raf);window.removeEventListener('hashchange',scroll);};
  },[route]);
  useEffect(()=>{
    if(!restoreFocus.current)return;
    const raf=requestAnimationFrame(()=>document.querySelector(`[data-episode="${selected}"], [data-key="${selected}"]`)?.focus());
    return ()=>cancelAnimationFrame(raf);
  },[selected]);
  const episode=episodes.find(item=>item.id===selected);
  return <EpisodeExperience key={route+selected} vlog={route==='vlog.html'} episodes={episodes} episode={episode} originalData={originalData} dimensions={dimensions} onSelect={id=>{restoreFocus.current=true;setSelected(id);}}/>;
}
function EpisodeExperience({vlog,episodes,episode,originalData,dimensions,onSelect}){
  const player=usePhotoPlayer(episode);
  const [expanded,setExpanded]=useState(null);
  const id=vlog?'vlog':'original';
  const openPhoto=photo=>{player.pause();setExpanded(photo);};
  const scenes=<>{episode.scenes.map((photo,index)=><button key={photo.full} type="button" disabled={!player.hydrated} aria-label={vlog?`장면 ${index+1}, ${clock(index*secondsPerScene)}로 이동`:`장면 ${index+1} ${photo.label}`} aria-current={index===player.index?'true':'false'} onClick={()=>player.jump(index*secondsPerScene)}><img src={photo.thumb} alt="" loading="lazy" decoding="async" {...imageProps(dimensions,photo.thumb)}/>{vlog?<span>{String(index+1).padStart(2,'0')} · {clock(index*secondsPerScene)}</span>:<span>{photo.label}<small>{clock(index*secondsPerScene)}</small></span>}</button>)}</>;
  const playText=player.playing?'Ⅱ 일시정지':player.elapsed>=player.duration?'↻ 다시 재생':'▶ 재생';
  const controls=<><label className={vlog?'vlog-sr-only':'nc-sr-only'} htmlFor={id+'Seek'}>재생 위치</label><input id={id+'Seek'} type="range" min="0" max={player.duration} step="0.1" value={player.elapsed} disabled={!player.hydrated} aria-valuetext={`${clock(player.elapsed)} / ${clock(player.duration)}`} onChange={event=>player.jump(Number(event.target.value))}/><div className={vlog?'vlog-control-row':'nc-control-row'}><button id={id+'Play'} type="button" disabled={!player.hydrated} aria-label={player.playing?'일시정지':player.elapsed>=player.duration?'처음부터 다시 재생':'재생'} onClick={player.toggle}>{playText}</button><button id={id+'Prev'} type="button" aria-label="이전 장면" disabled={!player.hydrated||player.index===0} onClick={()=>player.jump((player.index-1)*secondsPerScene)}>이전</button><button id={id+'Next'} type="button" aria-label="다음 장면" disabled={!player.hydrated||player.index===episode.scenes.length-1} onClick={()=>player.jump((player.index+1)*secondsPerScene)}>다음</button>{vlog?<><span id="vlogTime" className="vlog-time">{clock(player.elapsed)} / {clock(player.duration)}</span><span id="vlogScene" className="vlog-scene">{String(player.index+1).padStart(2,'0')} / {episode.scenes.length}</span></>:<><output id="originalTime">{clock(player.elapsed)} / {clock(player.duration)}</output><button id="originalExpand" type="button" disabled={!player.hydrated} onClick={()=>openPhoto(episode.scenes[player.index])}>크게 보기</button></>}</div></>;
  const screen=<><img ref={player.frameRef} id={id+'Frame'} src={player.frame.full} alt={player.frame.label} fetchPriority="high" decoding="async" {...imageProps(dimensions,player.frame.full)}/><p className={vlog?'vlog-screen-status':undefined} id={vlog?'vlogStatus':'loadStatus'} role="status" hidden={!player.status}>{player.status}</p></>;
  if(vlog)return <main className="container vlog-main"><div className="vlog-heading"><div><p className="vlog-kicker">OFF THE STAGE / 06 EPISODES</p><h1>NIGHT VLOG</h1></div><p>사진으로 이어 보는, 우리의 하루.<br/><span>이미지 슬라이드 · 음성 없음</span></p></div><div className="vlog-layout"><section className="vlog-watch" aria-label="브이로그 감상"><div className="vlog-player" id="vlogPlayer" tabIndex="0" aria-label="사진 브이로그 플레이어" onKeyDown={event=>{if(event.target!==event.currentTarget||event.altKey||event.ctrlKey||event.metaKey)return;if(event.key===' '){event.preventDefault();player.toggle();}if(event.key==='ArrowLeft'){event.preventDefault();player.jump((player.index-1)*secondsPerScene);}if(event.key==='ArrowRight'){event.preventDefault();player.jump((player.index+1)*secondsPerScene);}}}><div className="vlog-screen" id="vlogScreen">{screen}</div><div className="vlog-controls">{controls}</div></div><div className="vlog-episode-head"><p className="vlog-kicker" id="vlogOwner">{episode.owner}</p><h2 id="vlogTitle">{episode.title}</h2><p id="vlogDescription">{episode.description}</p></div><p className="vlog-help">장면당 6초 · 사진을 더 보고 싶다면 일시정지해 주세요.</p><nav className="vlog-scenes" id="vlogScenes" aria-label="장면 바로 이동">{scenes}</nav><section className="vlog-reactions" aria-labelledby="reactionHeading"><div><p className="vlog-kicker">AFTER WATCHING</p><h2 id="reactionHeading">LUNA REACTIONS</h2><p>함께 보는 팬 반응 이미지</p></div><a id="vlogReactionLink" href={vlogReaction(episode)} target="_blank" rel="noopener"><img id="vlogReaction" src={vlogReaction(episode)} alt={`${episode.title} 팬 반응 이미지`} loading="lazy" decoding="async" {...imageProps(dimensions,vlogReaction(episode))}/><span>원본 크게 보기 ↗</span></a></section></section><aside className="vlog-playlist" aria-labelledby="playlistHeading"><h2 id="playlistHeading">EPISODES <span>6</span></h2><div id="vlogEpisodes">{episodes.map(item=><button key={item.id} type="button" className="vlog-episode" data-episode={item.id} disabled={!player.hydrated} aria-label={`${item.owner}, ${item.short} 선택`} aria-current={item.id===episode.id?'true':'false'} onClick={()=>onSelect(item.id)}><img src={item.scenes[0].thumb} alt="" loading="lazy" decoding="async" {...imageProps(dimensions,item.scenes[0].thumb)}/><span><small>{item.owner}</small><strong>{item.short}</strong><em>{item.scenes.length} SCENES · {clock(item.scenes.length*secondsPerScene)}</em></span></button>)}</div></aside></div></main>;
  return <><main className="container nc-main"><div className="nc-heading"><p className="nc-kicker">PHOTO EPISODES / 05</p><h1>NIGHT ORIGINALS</h1><p>호텔, 야근, 캠핑, 꽃집 그리고 진짜 막내. 장면으로 이어 보는 NIGHT의 자체 콘텐츠.</p></div><div className="nc-tabs" id="episodeTabs" role="group" aria-label="콘텐츠 선택">{episodes.map(item=><button key={item.id} type="button" data-key={item.id} disabled={!player.hydrated} aria-pressed={item.id===episode.id} onClick={()=>onSelect(item.id)}>{item.title}</button>)}</div><div className="nc-original-layout"><section className="nc-watch" aria-label="에피소드 플레이어"><div className="nc-player"><div className="nc-screen">{screen}</div><div className="nc-controls">{controls}</div></div><p className="nc-kicker nc-player-note">PHOTO SLIDES · 음성 없음 · 장면당 6초</p><h2 id="originalTitle">{episode.title}</h2><p id="originalCaption">{String(player.index+1).padStart(2,'0')} / {episode.scenes[player.index].label}</p><section id="originalExtras" className="nc-extras" aria-label="추가 장면">{episode.extras.length>0&&<><h2>AFTER THE EPISODE</h2>{episode.extras.map(photo=><PhotoCard key={photo.full} photo={photo} onOpen={openPhoto} dimensions={dimensions}/>)}</>}{episode.id==='flowers'&&<a className="nc-text-link" href="#for-luna">LUNA에게 전하는 꽃다발 · SPECIAL PHOTO ↗</a>}</section></section><aside><h2 className="nc-side-heading">SCENES</h2><div id="originalScenes" className="nc-scene-list">{scenes}</div></aside></div><section className="nc-flower-section" id="for-luna"><p className="nc-kicker">FLOWER SHOP / SPECIAL PHOTO</p><h2>FOR LUNA</h2><p>하루의 끝에, 너에게 주고 싶은 꽃다발.</p><div id="flowerPhotos" className="nc-photo-grid nc-flower-grid">{originalData.flowers.map(photo=><PhotoCard key={photo.full} photo={photo} onOpen={openPhoto} dimensions={dimensions}/>)}</div><a className="nc-text-link" href="with-luna.html">WITH LUNA에서 하루 더 함께하기 ↗</a></section></main><CollectionPhotoDialog photo={expanded} onClose={()=>setExpanded(null)} dimensions={dimensions}/></>;
}
