import {useEffect,useState} from 'react';
import {woohyunNightOff,woohyunNightOffImages} from '../data/woohyunNightOff.mjs';

const numberLabel=number=>String(number).padStart(2,'0');

export function WoohyunNightOffPage(){
  const {program,schedule,corners,guests,moments}=woohyunNightOff;
  const [activePhoto,setActivePhoto]=useState(null);
  useEffect(()=>{if(activePhoto===null)return;const onKey=event=>{if(event.key==='Escape')setActivePhoto(null);if(event.key==='ArrowLeft')setActivePhoto(index=>(index-1+moments.length)%moments.length);if(event.key==='ArrowRight')setActivePhoto(index=>(index+1)%moments.length);};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey);},[activePhoto,moments.length]);
  return <main className="night-off-archive">
    <section className="night-off-hero"><div className="container"><p className="night-off-member">WOOHYUN</p><p className="night-off-kicker">PERSONAL SCHEDULE</p><h1>WOOHYUN'S<br/>NIGHT OFF</h1><p className="night-off-korean">우현의 나이트 오프</p><div className="night-off-hero-meta"><span>RADIO · {program.period}</span><span>{program.schedule}</span><span>{program.host}</span></div></div></section>
    <nav className="night-off-nav" aria-label="우현의 나이트 오프 섹션"><div className="container"><a href="#program-intro">PROGRAM</a><a href="#weekly-corners">WEEKLY CORNERS</a><a href="#corner-guide">CORNER GUIDE</a><a href="#guests-visible-radio">GUESTS &amp; VISIBLE RADIO</a><a href="#night-off-moments">MOMENTS</a></div></nav>
    <section className="night-off-intro" id="program-intro" aria-labelledby="program-intro-title"><div className="container night-off-intro-grid"><header><span>PROGRAM INTRO</span><h2 id="program-intro-title">FRIDAY,<br/>10 PM</h2></header><div className="night-off-prose">{program.intro.map(text=><p key={text}>{text}</p>)}</div></div></section>
    <section className="night-off-weekly" id="weekly-corners" aria-labelledby="weekly-corners-title"><div className="container"><header className="night-off-section-head"><div><span>BIWEEKLY PROGRAM</span><h2 id="weekly-corners-title">WEEKLY CORNERS</h2></div><small>1·3주 / 2·4주</small></header><div className="night-off-schedule">{schedule.map(group=><article key={group.weeks}><h3>{group.weeks}</h3><div>{group.parts.map(item=><a href={`#${item.slug}`} key={item.slug}><small>{item.part}</small><strong>{item.title}</strong><span>VIEW CORNER →</span></a>)}</div></article>)}</div></div></section>
    <section className="night-off-corners" id="corner-guide" aria-labelledby="corner-guide-title"><div className="container"><header className="night-off-section-head"><div><span>PROGRAM GUIDE</span><h2 id="corner-guide-title">FOUR CORNERS</h2></div><small>EVERY OTHER WEEK</small></header><div className="night-off-corner-list">{corners.map((corner,index)=><article id={corner.slug} key={corner.slug}><div className="night-off-corner-number">{numberLabel(index+1)}</div><header><span>{corner.weeks} · {corner.part}</span><h3>{corner.title}</h3></header><div>{corner.description.map(text=><p key={text}>{text}</p>)}</div></article>)}</div></div></section>
    <section className="night-off-guests" id="guests-visible-radio" aria-labelledby="guests-title"><div className="container night-off-guests-grid"><header><span>STUDIO &amp; BEHIND</span><h2 id="guests-title">GUESTS &amp;<br/>VISIBLE RADIO</h2></header><div className="night-off-prose">{guests.map(text=><p key={text}>{text}</p>)}</div></div></section>
    <section className="night-off-moments" id="night-off-moments" aria-labelledby="moments-title"><div className="container"><header className="night-off-section-head"><div><span>RADIO ARCHIVE</span><h2 id="moments-title">NIGHT OFF MOMENTS</h2></div><small>9 MOMENTS</small></header><div className="night-off-moments-grid">{moments.map((moment,index)=><button className={`night-off-moment${moment.number===1?' night-off-moment-featured':''}`} type="button" onClick={()=>setActivePhoto(index)} aria-label={`${moment.label} 사진 크게 보기`} key={moment.image}><img src={moment.image} alt={`${moment.label} — ${moment.description}`} loading={moment.number===1?'eager':'lazy'} decoding="async"/><span><small>{numberLabel(moment.number)}</small><strong>{moment.label}</strong><em>{moment.description}</em></span></button>)}</div></div></section>
    {activePhoto!==null?<div className="night-off-lightbox" role="dialog" aria-modal="true" aria-label="우현의 나이트 오프 사진 크게 보기" onClick={event=>{if(event.target===event.currentTarget)setActivePhoto(null);}}><button className="night-off-lightbox-close" type="button" onClick={()=>setActivePhoto(null)} aria-label="닫기">×</button><button type="button" onClick={()=>setActivePhoto(index=>(index-1+moments.length)%moments.length)} aria-label="이전 사진">‹</button><figure><img src={woohyunNightOffImages[activePhoto]} alt={moments[activePhoto].description}/><figcaption>{moments[activePhoto].label} · {numberLabel(activePhoto+1)} / {moments.length}</figcaption></figure><button type="button" onClick={()=>setActivePhoto(index=>(index+1)%moments.length)} aria-label="다음 사진">›</button></div>:null}
  </main>;
}
